[package]
name = "Laze"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peg_parser = { path = "vendor/peg_parser" }